version: '3'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgsql-data:/var/lib/postgresql/data

volumes:
  pgsql-data:
